### ISSUE TITLE
What is vector size of LSTM and number of neurons. How is it related to input embedding size?

### ISSUE THREAD

**Issue by prats226** [jagadeeshraja/quora_duplicate_detection#3]
https://github.com/jagadeeshraja/quora_duplicate_detection/blob/0730316f46a6b6bd520bbf01ff1429f3c857322f/src/deep_learning_duplicate_prediction.py#L39

**Comment by jagadeeshraja** [comment]
I am taking the total_number_of_words as inputs to initial embedding layer -> from there I am creating a 300/100 dimensional vector.. (the reason its 100/300 is because I am running multiple versions and evaluating the performance.. will be cleaning this up soon.)

This 100/300 dim vector is fed into LSTM... here inside LSTM 300 should refer to the size of the output of LSTM..

**Comment by jagadeeshraja** [comment]
Structure of LSTM and how the weights interact...
![alt text](http://colah.github.io/posts/2015-08-Understanding-LSTMs/img/LSTM3-var-GRU.png "LSTM 1")
